"""Hằng reward — sync từ PC Learn Lab (modules/logics/reward_config.py)."""

R_STEP = 0
R_COLLISION = 0
R_GOAL_CLOSER = 0
R_GOAL_FARTHER = 0.0
R_CP_CLOSER = 0
R_CP_FARTHER = 0.0
R_CHECKPOINT_FIRST = 0
R_GOAL_REACHED = 100
R_ROTATE_IN_PLACE = 0
R_FACING_CLEAR = 0
R_FORWARD_CLEAR = 0
R_WASTED_ROTATE = 0
MAX_ROTATE_STREAK = 4
MAX_NODE_REVISITS = 5
MAX_PING_PONG_CYCLES = 2
COLLISION_RESET = False
MAX_STEPS_PER_EPISODE = 600
