"""Hằng reward — sync từ PC Learn Lab (modules/logics/reward_config.py)."""

R_STEP = -1.0
R_COLLISION = -20.0
R_GOAL_CLOSER = 5.0
R_GOAL_FARTHER = 0.0
R_CP_CLOSER = 8.0
R_CP_FARTHER = 0.0
R_CHECKPOINT_FIRST = 30.0
R_GOAL_REACHED = 100.0
R_ROTATE_IN_PLACE = -3.0
R_FACING_CLEAR = 5.0
R_FORWARD_CLEAR = 4.0
R_WASTED_ROTATE = -12.0
MAX_ROTATE_STREAK = 4
MAX_NODE_REVISITS = 5
MAX_PING_PONG_CYCLES = 2
COLLISION_RESET = False
MAX_STEPS_PER_EPISODE = 600
